name: agri_sense_360
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.0.0
  geolocator: ^14.0.2
  image_picker: ^1.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add your image assets here
  assets:
    - lib/images/farming_image.jpg
    - lib/images/irrigation_image.jpg
    - lib/images/data_insights_image.jpg
    - lib/images/logo.png
    - lib/images/soil_image.jpg
    - lib/images/crops_image.jpg
    - lib/images/greenhouse_image.jpg
    - lib/images/nitrate_image.jpg
